project_name: clay

release:
  make_latest: true
  mode: keep-existing

builds:
  - id: "clay"
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
    binary: clay
    main: ./main.go
    ldflags: -s -w
    env:
      - CGO_ENABLED=0

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs"
      - "^test"
      - "^build"
      - "^chore"
      - "^Merge pull request"

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-next"

brews:
  - repository:
      owner: pixxelhq
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/pixxelhq/clay"
    description: "CLI for packaging ML models as deployable blocks"
    license: "Apache-2.0"
    install: |
      bin.install "clay"
    test: |
      system "#{bin}/clay", "version"
