project_name: clay

release:
  make_latest: true
  mode: keep-existing

builds:
  - id: "clay"
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
    binary: clay
    main: ./main.go
    ldflags: -s -w
    env:
      - CGO_ENABLED=0

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs"
      - "^test"
      - "^build"
      - "^chore"
      - "^Merge pull request"

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-next"

# TODO: add a `brews:` section here so `brew install clay`

