# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: "clay/templates"
repos:

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.11
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format
        name: Formatting with Ruff

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: [--allow-multiple-documents]
        exclude: api/bootstrap/templates/
      - id: check-added-large-files

  - repo: https://github.com/asottile/yesqa
    rev: v1.4.0
    hooks:
      - id: yesqa
        name: Unused noqa

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.343
    hooks:
      - id: pyright
        name: Type Checking with Pyright
        args: [ --project=pyright-config.json ]

  - repo: https://github.com/TekWizely/pre-commit-golang
    rev: v1.0.0-rc.1
    hooks:
      - id: go-fmt
        name: Format Go programs

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v2.1.1
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
