// Package api_docs Code generated by swaggo/swag. DO NOT EDIT
package api_docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "MLOps team",
            "email": "mlops@pixxel.co.in"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/blocks": {
            "get": {
                "description": "Return all the blocks with latest version.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Block"
                ],
                "summary": "Get the latest blocks from the registry",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http.RegistryResponse-http_GetLatestBlocksResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/http.RegistryResponse-any"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/http.RegistryResponse-any"
                        }
                    }
                }
            },
            "post": {
                "description": "publish the specific version of the block.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Block"
                ],
                "summary": "Publish the block to clay registry",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http.RegistryResponse-http_CreateBlockResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/http.RegistryResponse-any"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/http.RegistryResponse-any"
                        }
                    }
                }
            }
        },
        "/v1/blocks/{name}": {
            "get": {
                "description": "Returns all the versions of the block name.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Block"
                ],
                "summary": "Get block by name.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Name of the block",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http.RegistryResponse-http_GetBlockByNameResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/http.RegistryResponse-any"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/http.RegistryResponse-any"
                        }
                    }
                }
            }
        },
        "/v1/blocks/{name}/versions/{version}": {
            "get": {
                "description": "Returns the block for the given version and name.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Block"
                ],
                "summary": "Get block by name and version.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Name of the block",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Version of the block",
                        "name": "version",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http.RegistryResponse-http_GetBlockVersion"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/http.RegistryResponse-any"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/http.RegistryResponse-any"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "http.CreateBlockResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "specification": {
                    "$ref": "#/definitions/http.Specification"
                },
                "type": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "http.GetBlockVersion": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "kind": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "specification": {
                    "$ref": "#/definitions/http.Specification"
                },
                "type": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "http.GetLatestBlock": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "specification": {
                    "$ref": "#/definitions/http.Specification"
                },
                "type": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "http.RegistryResponse-any": {
            "type": "object",
            "properties": {
                "data": {},
                "error": {
                    "type": "string"
                }
            }
        },
        "http.RegistryResponse-http_CreateBlockResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/http.CreateBlockResponse"
                },
                "error": {
                    "type": "string"
                }
            }
        },
        "http.RegistryResponse-http_GetBlockByNameResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/http.GetBlockVersion"
                    }
                },
                "error": {
                    "type": "string"
                }
            }
        },
        "http.RegistryResponse-http_GetBlockVersion": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/http.GetBlockVersion"
                },
                "error": {
                    "type": "string"
                }
            }
        },
        "http.RegistryResponse-http_GetLatestBlocksResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/http.GetLatestBlock"
                    }
                },
                "error": {
                    "type": "string"
                }
            }
        },
        "http.Specification": {
            "type": "object",
            "properties": {
                "apiVersion": {
                    "type": "string"
                },
                "author": {
                    "type": "string"
                },
                "build": {
                    "type": "object"
                },
                "description": {
                    "type": "string"
                },
                "inputs": {
                    "type": "object"
                },
                "outputs": {
                    "type": "object"
                },
                "parameters": {
                    "type": "object"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "title": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Clay Registry",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
