// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: block_version.sql

package store

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
)

const createBlockVersion = `-- name: CreateBlockVersion :one
INSERT INTO
    public.block_versions (
        block_id,
        version,
        specification,
        documentation_url,
        thumbnail_url,
        catalog,
        docker_image
    )
VALUES
    (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7
    ) RETURNING id, version, block_id, specification, documentation_url, docker_image, created_at, updated_at, thumbnail_url, catalog
`

type CreateBlockVersionParams struct {
	BlockID          uuid.UUID
	Version          string
	Specification    json.RawMessage
	DocumentationUrl sql.NullString
	ThumbnailUrl     sql.NullString
	Catalog          json.RawMessage
	DockerImage      sql.NullString
}

func (q *Queries) CreateBlockVersion(ctx context.Context, arg CreateBlockVersionParams) (BlockVersion, error) {
	row := q.db.QueryRowContext(ctx, createBlockVersion,
		arg.BlockID,
		arg.Version,
		arg.Specification,
		arg.DocumentationUrl,
		arg.ThumbnailUrl,
		arg.Catalog,
		arg.DockerImage,
	)
	var i BlockVersion
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.BlockID,
		&i.Specification,
		&i.DocumentationUrl,
		&i.DockerImage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ThumbnailUrl,
		&i.Catalog,
	)
	return i, err
}

const getBlockAllVersionByName = `-- name: GetBlockAllVersionByName :many
SELECT
    b.id,
    b.name,
    b.type,
    b.kind,
    bv.version,
    bv.specification,
    bv.documentation_url,
    bv.thumbnail_url,
    bv.docker_image,
    bv.created_at,
    bv.updated_at
FROM public.block_versions bv
    INNER JOIN public.blocks b
    ON bv.block_id = b.id
WHERE b.name = $1
ORDER BY b.id, bv.version desc
`

type GetBlockAllVersionByNameRow struct {
	ID               uuid.UUID
	Name             string
	Type             string
	Kind             string
	Version          string
	Specification    json.RawMessage
	DocumentationUrl sql.NullString
	ThumbnailUrl     sql.NullString
	DockerImage      sql.NullString
	CreatedAt        sql.NullTime
	UpdatedAt        sql.NullTime
}

func (q *Queries) GetBlockAllVersionByName(ctx context.Context, name string) ([]GetBlockAllVersionByNameRow, error) {
	rows, err := q.db.QueryContext(ctx, getBlockAllVersionByName, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetBlockAllVersionByNameRow{}
	for rows.Next() {
		var i GetBlockAllVersionByNameRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Kind,
			&i.Version,
			&i.Specification,
			&i.DocumentationUrl,
			&i.ThumbnailUrl,
			&i.DockerImage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBlockByNameAndVersion = `-- name: GetBlockByNameAndVersion :one
SELECT
    b.id,
    b.name,
    bv.version,
    b.type,
    b.kind,
    bv.specification,
    bv.documentation_url,
    bv.thumbnail_url,
    bv.docker_image,
    bv.created_at,
    bv.updated_at
FROM public.block_versions bv
    INNER JOIN public.blocks b
    ON bv.block_id = b.id
WHERE b.name = $1 and bv.version = $2
`

type GetBlockByNameAndVersionParams struct {
	Name    string
	Version string
}

type GetBlockByNameAndVersionRow struct {
	ID               uuid.UUID
	Name             string
	Version          string
	Type             string
	Kind             string
	Specification    json.RawMessage
	DocumentationUrl sql.NullString
	ThumbnailUrl     sql.NullString
	DockerImage      sql.NullString
	CreatedAt        sql.NullTime
	UpdatedAt        sql.NullTime
}

func (q *Queries) GetBlockByNameAndVersion(ctx context.Context, arg GetBlockByNameAndVersionParams) (GetBlockByNameAndVersionRow, error) {
	row := q.db.QueryRowContext(ctx, getBlockByNameAndVersion, arg.Name, arg.Version)
	var i GetBlockByNameAndVersionRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Version,
		&i.Type,
		&i.Kind,
		&i.Specification,
		&i.DocumentationUrl,
		&i.ThumbnailUrl,
		&i.DockerImage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
