// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: block.sql

package store

import (
	"context"
)

const createBlock = `-- name: CreateBlock :one
INSERT INTO 
    public.blocks (
        name,
        kind,
        type
    )
VALUES
    (
        $1,
        $2,
        $3
    ) RETURNING id, name, kind, type, created_at, updated_at
`

type CreateBlockParams struct {
	Name string
	Kind string
	Type string
}

func (q *Queries) CreateBlock(ctx context.Context, arg CreateBlockParams) (Block, error) {
	row := q.db.QueryRowContext(ctx, createBlock, arg.Name, arg.Kind, arg.Type)
	var i Block
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
