// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: block.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const getAllBlocks = `-- name: GetAllBlocks :many
SELECT
    id,
    name,
    kind,
    type,
    created_at,
    updated_at
FROM
    public.blocks
`

func (q *Queries) GetAllBlocks(ctx context.Context) ([]Block, error) {
	rows, err := q.db.QueryContext(ctx, getAllBlocks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Block{}
	for rows.Next() {
		var i Block
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Kind,
			&i.Type,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBlock = `-- name: GetBlock :one
SELECT
    id,
    name,
    kind,   
    type,
    created_at,
    updated_at
FROM 
    public.blocks
WHERE 
    id = $1
`

func (q *Queries) GetBlock(ctx context.Context, id uuid.UUID) (Block, error) {
	row := q.db.QueryRowContext(ctx, getBlock, id)
	var i Block
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertBlock = `-- name: UpsertBlock :one
INSERT INTO 
    public.blocks (
        name,
        kind,
        type
    )
VALUES
    (
        $1,
        $2,
        $3
    ) 
ON CONFLICT(name) 
DO UPDATE SET 
    name = EXCLUDED.name
RETURNING id, name, kind, type, created_at, updated_at
`

type UpsertBlockParams struct {
	Name string
	Kind string
	Type string
}

func (q *Queries) UpsertBlock(ctx context.Context, arg UpsertBlockParams) (Block, error) {
	row := q.db.QueryRowContext(ctx, upsertBlock, arg.Name, arg.Kind, arg.Type)
	var i Block
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
