// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: block_version.sql

package store

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
)

const createBlockVersion = `-- name: CreateBlockVersion :one
INSERT INTO 
    public.block_versions (
        block_id,
        version,
        specification,
        documenatation_url,
        docker_image
    )
VALUES
    (
        $1,
        $2,
        $3,
        $4,
        $5
    ) RETURNING id, version, block_id, specification, documenatation_url, docker_image, created_at, updated_at
`

type CreateBlockVersionParams struct {
	BlockID           uuid.UUID
	Version           string
	Specification     json.RawMessage
	DocumenatationUrl sql.NullString
	DockerImage       sql.NullString
}

func (q *Queries) CreateBlockVersion(ctx context.Context, arg CreateBlockVersionParams) (BlockVersion, error) {
	row := q.db.QueryRowContext(ctx, createBlockVersion,
		arg.BlockID,
		arg.Version,
		arg.Specification,
		arg.DocumenatationUrl,
		arg.DockerImage,
	)
	var i BlockVersion
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.BlockID,
		&i.Specification,
		&i.DocumenatationUrl,
		&i.DockerImage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBlocksWithLatestVersion = `-- name: GetBlocksWithLatestVersion :many
SELECT distinct on (b.id)
    b.id,
    b.name,
    bv.version,
    bv.specification,
    bv.documenatation_url,
    bv.docker_image,
    bv.created_at,
    bv.updated_at
FROM public.block_versions bv 
    INNER JOIN public.blocks b
    ON bv.block_id = b.id
ORDER BY b.id, bv.version desc
`

type GetBlocksWithLatestVersionRow struct {
	ID                uuid.UUID
	Name              string
	Version           string
	Specification     json.RawMessage
	DocumenatationUrl sql.NullString
	DockerImage       sql.NullString
	CreatedAt         sql.NullTime
	UpdatedAt         sql.NullTime
}

func (q *Queries) GetBlocksWithLatestVersion(ctx context.Context) ([]GetBlocksWithLatestVersionRow, error) {
	rows, err := q.db.QueryContext(ctx, getBlocksWithLatestVersion)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetBlocksWithLatestVersionRow{}
	for rows.Next() {
		var i GetBlocksWithLatestVersionRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Version,
			&i.Specification,
			&i.DocumenatationUrl,
			&i.DockerImage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
