// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: block_version.sql

package store

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
)

const createBlockVersion = `-- name: CreateBlockVersion :one
INSERT INTO 
    public.block_versions (
        block_id,
        version,
        specification,
        documentation_url,
        docker_image
    )
VALUES
    (
        $1,
        $2,
        $3,
        $4,
        $5
    ) RETURNING id, version, block_id, specification, documentation_url, docker_image, created_at, updated_at
`

type CreateBlockVersionParams struct {
	BlockID          uuid.UUID
	Version          string
	Specification    json.RawMessage
	DocumentationUrl sql.NullString
	DockerImage      sql.NullString
}

func (q *Queries) CreateBlockVersion(ctx context.Context, arg CreateBlockVersionParams) (BlockVersion, error) {
	row := q.db.QueryRowContext(ctx, createBlockVersion,
		arg.BlockID,
		arg.Version,
		arg.Specification,
		arg.DocumentationUrl,
		arg.DockerImage,
	)
	var i BlockVersion
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.BlockID,
		&i.Specification,
		&i.DocumentationUrl,
		&i.DockerImage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBlockAllVersionByName = `-- name: GetBlockAllVersionByName :many
SELECT
    b.id,
    b.name,
    b.type,
    b.kind,
    bv.version,
    bv.specification,
    bv.documentation_url,
    bv.docker_image,
    bv.created_at,
    bv.updated_at
FROM public.block_versions bv
    INNER JOIN public.blocks b
    ON bv.block_id = b.id
WHERE b.name = $1
ORDER BY b.id, bv.version desc
`

type GetBlockAllVersionByNameRow struct {
	ID               uuid.UUID
	Name             string
	Type             string
	Kind             string
	Version          string
	Specification    json.RawMessage
	DocumentationUrl sql.NullString
	DockerImage      sql.NullString
	CreatedAt        sql.NullTime
	UpdatedAt        sql.NullTime
}

func (q *Queries) GetBlockAllVersionByName(ctx context.Context, name string) ([]GetBlockAllVersionByNameRow, error) {
	rows, err := q.db.QueryContext(ctx, getBlockAllVersionByName, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetBlockAllVersionByNameRow{}
	for rows.Next() {
		var i GetBlockAllVersionByNameRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Kind,
			&i.Version,
			&i.Specification,
			&i.DocumentationUrl,
			&i.DockerImage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBlockByNameAndVersion = `-- name: GetBlockByNameAndVersion :one
SELECT
    b.id,
    b.name,
    bv.version,
    b.type,
    b.kind,
    bv.specification,
    bv.documentation_url,
    bv.docker_image,
    bv.created_at,
    bv.updated_at
FROM public.block_versions bv
    INNER JOIN public.blocks b
    ON bv.block_id = b.id
WHERE b.name = $1 and bv.version = $2
`

type GetBlockByNameAndVersionParams struct {
	Name    string
	Version string
}

type GetBlockByNameAndVersionRow struct {
	ID               uuid.UUID
	Name             string
	Version          string
	Type             string
	Kind             string
	Specification    json.RawMessage
	DocumentationUrl sql.NullString
	DockerImage      sql.NullString
	CreatedAt        sql.NullTime
	UpdatedAt        sql.NullTime
}

func (q *Queries) GetBlockByNameAndVersion(ctx context.Context, arg GetBlockByNameAndVersionParams) (GetBlockByNameAndVersionRow, error) {
	row := q.db.QueryRowContext(ctx, getBlockByNameAndVersion, arg.Name, arg.Version)
	var i GetBlockByNameAndVersionRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Version,
		&i.Type,
		&i.Kind,
		&i.Specification,
		&i.DocumentationUrl,
		&i.DockerImage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBlocksWithLatestVersion = `-- name: GetBlocksWithLatestVersion :many
SELECT distinct on (b.id)
    b.id,
    b.name,
    b.type,
    b.kind,
    bv.version,
    bv.specification,
    bv.documentation_url,
    bv.docker_image,
    bv.created_at,
    bv.updated_at
FROM public.block_versions bv 
    INNER JOIN public.blocks b
    ON bv.block_id = b.id
ORDER BY b.id, string_to_array(regexp_replace(bv.version, '^v', ''), '.')::int[] desc
`

type GetBlocksWithLatestVersionRow struct {
	ID               uuid.UUID
	Name             string
	Type             string
	Kind             string
	Version          string
	Specification    json.RawMessage
	DocumentationUrl sql.NullString
	DockerImage      sql.NullString
	CreatedAt        sql.NullTime
	UpdatedAt        sql.NullTime
}

func (q *Queries) GetBlocksWithLatestVersion(ctx context.Context) ([]GetBlocksWithLatestVersionRow, error) {
	rows, err := q.db.QueryContext(ctx, getBlocksWithLatestVersion)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetBlocksWithLatestVersionRow{}
	for rows.Next() {
		var i GetBlocksWithLatestVersionRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Kind,
			&i.Version,
			&i.Specification,
			&i.DocumentationUrl,
			&i.DockerImage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestBlockByName = `-- name: GetLatestBlockByName :one
SELECT
    b.id,
    b.name,
    bv.version,
    b.type,
    b.kind,
    bv.specification,
    bv.documentation_url,
    bv.docker_image,
    bv.created_at,
    bv.updated_at
FROM public.block_versions bv
    INNER JOIN public.blocks b
    ON bv.block_id = b.id
WHERE b.name = $1
ORDER BY string_to_array(regexp_replace(bv.version, '^v', ''), '.')::int[] DESC
LIMIT 1
`

type GetLatestBlockByNameRow struct {
	ID               uuid.UUID
	Name             string
	Version          string
	Type             string
	Kind             string
	Specification    json.RawMessage
	DocumentationUrl sql.NullString
	DockerImage      sql.NullString
	CreatedAt        sql.NullTime
	UpdatedAt        sql.NullTime
}

func (q *Queries) GetLatestBlockByName(ctx context.Context, name string) (GetLatestBlockByNameRow, error) {
	row := q.db.QueryRowContext(ctx, getLatestBlockByName, name)
	var i GetLatestBlockByNameRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Version,
		&i.Type,
		&i.Kind,
		&i.Specification,
		&i.DocumentationUrl,
		&i.DockerImage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
