// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package store

import (
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
)

type Block struct {
	ID        uuid.UUID
	Name      string
	Kind      string
	Type      string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type BlockVersion struct {
	ID               uuid.UUID
	Version          string
	BlockID          uuid.UUID
	Specification    json.RawMessage
	DocumentationUrl sql.NullString
	DockerImage      sql.NullString
	CreatedAt        sql.NullTime
	UpdatedAt        sql.NullTime
	ThumbnailUrl     sql.NullString
	CatalogUrl       sql.NullString
}
