// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package store

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateBlockVersion(ctx context.Context, arg CreateBlockVersionParams) (BlockVersion, error)
	GetBlock(ctx context.Context, id uuid.UUID) (Block, error)
	GetBlocksWithLatestVersion(ctx context.Context) ([]GetBlocksWithLatestVersionRow, error)
	UpsertBlock(ctx context.Context, arg UpsertBlockParams) (Block, error)
}

var _ Querier = (*Queries)(nil)
