// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package store

import (
	"context"
)

type Querier interface {
	CreateBlock(ctx context.Context, arg CreateBlockParams) (Block, error)
}

var _ Querier = (*Queries)(nil)
