stages:
  - "test"
  - "Static Code Analysis"
  - "Docs"

.common_job_setup:
  image: "python:3.8"
  before_script:
    - echo "Starting before_script"
    - pip install -r python/requirements/requirements-dev.txt
    - pip install coverage mypy flake8 isort sphinx pre-commit

code-formatting-flake8:
  stage: "Static Code Analysis"
  extends: .common_job_setup
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  script:
    - flake8 .

code-formatting-mypy:
  stage: "Static Code Analysis"
  extends: .common_job_setup
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  script:
    - mypy .

code-formatting-isort:
  stage: "Static Code Analysis"
  extends: .common_job_setup
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  script:
    - isort . --check

docs-build:
  stage: "Docs"
  extends: .common_job_setup
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  script:
    - make docs

pytest-all:
  stage: test
  extends: .common_job_setup
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  script:
    - coverage run -m pytest -v --junitxml=pytest-report.xml
    - coverage report
    - coverage xml
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
      junit: pytest-report.xml
