// Code generated by MockGen. DO NOT EDIT.
// Source: registry/internal/store/sqlc (interfaces: Store)

// Package mock_store is a generated GoMock package.
package mock_store

import (
	context "context"
	reflect "reflect"
	store "registry/internal/store/sqlc"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// CreateBlockVersion mocks base method.
func (m *MockStore) CreateBlockVersion(arg0 context.Context, arg1 store.CreateBlockVersionParams) (store.BlockVersion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBlockVersion", arg0, arg1)
	ret0, _ := ret[0].(store.BlockVersion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBlockVersion indicates an expected call of CreateBlockVersion.
func (mr *MockStoreMockRecorder) CreateBlockVersion(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBlockVersion", reflect.TypeOf((*MockStore)(nil).CreateBlockVersion), arg0, arg1)
}

// ExecWithTx mocks base method.
func (m *MockStore) ExecWithTx(arg0 context.Context, arg1 func(store.Querier) (interface{}, error)) (interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecWithTx", arg0, arg1)
	ret0, _ := ret[0].(interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecWithTx indicates an expected call of ExecWithTx.
func (mr *MockStoreMockRecorder) ExecWithTx(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecWithTx", reflect.TypeOf((*MockStore)(nil).ExecWithTx), arg0, arg1)
}

// GetBlock mocks base method.
func (m *MockStore) GetBlock(arg0 context.Context, arg1 uuid.UUID) (store.Block, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlock", arg0, arg1)
	ret0, _ := ret[0].(store.Block)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlock indicates an expected call of GetBlock.
func (mr *MockStoreMockRecorder) GetBlock(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlock", reflect.TypeOf((*MockStore)(nil).GetBlock), arg0, arg1)
}

// GetBlocksWithLatestVersion mocks base method.
func (m *MockStore) GetBlocksWithLatestVersion(arg0 context.Context) ([]store.GetBlocksWithLatestVersionRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlocksWithLatestVersion", arg0)
	ret0, _ := ret[0].([]store.GetBlocksWithLatestVersionRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlocksWithLatestVersion indicates an expected call of GetBlocksWithLatestVersion.
func (mr *MockStoreMockRecorder) GetBlocksWithLatestVersion(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlocksWithLatestVersion", reflect.TypeOf((*MockStore)(nil).GetBlocksWithLatestVersion), arg0)
}

// UpsertBlock mocks base method.
func (m *MockStore) UpsertBlock(arg0 context.Context, arg1 store.UpsertBlockParams) (store.Block, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertBlock", arg0, arg1)
	ret0, _ := ret[0].(store.Block)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertBlock indicates an expected call of UpsertBlock.
func (mr *MockStoreMockRecorder) UpsertBlock(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertBlock", reflect.TypeOf((*MockStore)(nil).UpsertBlock), arg0, arg1)
}
