// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/pixxelhq/clay/registry/internal/store/sqlc (interfaces: Store)
//
// Generated by this command:
//
//	mockgen --build_flags=--mod=mod -package mock_store -destination internal/store/mock/store.go github.com/pixxelhq/clay/registry/internal/store/sqlc Store
//

// Package mock_store is a generated GoMock package.
package mock_store

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	store "github.com/pixxelhq/clay/registry/internal/store/sqlc"
	gomock "go.uber.org/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// CreateBlockVersion mocks base method.
func (m *MockStore) CreateBlockVersion(ctx context.Context, arg store.CreateBlockVersionParams) (store.BlockVersion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBlockVersion", ctx, arg)
	ret0, _ := ret[0].(store.BlockVersion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBlockVersion indicates an expected call of CreateBlockVersion.
func (mr *MockStoreMockRecorder) CreateBlockVersion(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBlockVersion", reflect.TypeOf((*MockStore)(nil).CreateBlockVersion), ctx, arg)
}

// ExecWithTx mocks base method.
func (m *MockStore) ExecWithTx(ctx context.Context, fn func(store.Querier) (any, error)) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecWithTx", ctx, fn)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecWithTx indicates an expected call of ExecWithTx.
func (mr *MockStoreMockRecorder) ExecWithTx(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecWithTx", reflect.TypeOf((*MockStore)(nil).ExecWithTx), ctx, fn)
}

// GetAllBlocks mocks base method.
func (m *MockStore) GetAllBlocks(ctx context.Context) ([]store.Block, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllBlocks", ctx)
	ret0, _ := ret[0].([]store.Block)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllBlocks indicates an expected call of GetAllBlocks.
func (mr *MockStoreMockRecorder) GetAllBlocks(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllBlocks", reflect.TypeOf((*MockStore)(nil).GetAllBlocks), ctx)
}

// GetBlock mocks base method.
func (m *MockStore) GetBlock(ctx context.Context, id uuid.UUID) (store.Block, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlock", ctx, id)
	ret0, _ := ret[0].(store.Block)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlock indicates an expected call of GetBlock.
func (mr *MockStoreMockRecorder) GetBlock(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlock", reflect.TypeOf((*MockStore)(nil).GetBlock), ctx, id)
}

// GetBlockAllVersionByName mocks base method.
func (m *MockStore) GetBlockAllVersionByName(ctx context.Context, name string) ([]store.GetBlockAllVersionByNameRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlockAllVersionByName", ctx, name)
	ret0, _ := ret[0].([]store.GetBlockAllVersionByNameRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlockAllVersionByName indicates an expected call of GetBlockAllVersionByName.
func (mr *MockStoreMockRecorder) GetBlockAllVersionByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlockAllVersionByName", reflect.TypeOf((*MockStore)(nil).GetBlockAllVersionByName), ctx, name)
}

// GetBlockByNameAndVersion mocks base method.
func (m *MockStore) GetBlockByNameAndVersion(ctx context.Context, arg store.GetBlockByNameAndVersionParams) (store.GetBlockByNameAndVersionRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlockByNameAndVersion", ctx, arg)
	ret0, _ := ret[0].(store.GetBlockByNameAndVersionRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlockByNameAndVersion indicates an expected call of GetBlockByNameAndVersion.
func (mr *MockStoreMockRecorder) GetBlockByNameAndVersion(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlockByNameAndVersion", reflect.TypeOf((*MockStore)(nil).GetBlockByNameAndVersion), ctx, arg)
}

// UpsertBlock mocks base method.
func (m *MockStore) UpsertBlock(ctx context.Context, arg store.UpsertBlockParams) (store.Block, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertBlock", ctx, arg)
	ret0, _ := ret[0].(store.Block)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertBlock indicates an expected call of UpsertBlock.
func (mr *MockStoreMockRecorder) UpsertBlock(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertBlock", reflect.TypeOf((*MockStore)(nil).UpsertBlock), ctx, arg)
}
