// Code generated by MockGen. DO NOT EDIT.
// Source: registry/pkg/block (interfaces: Service)

// Package mock_block is a generated GoMock package.
package mock_block

import (
	context "context"
	reflect "reflect"
	block "registry/pkg/block"

	gomock "github.com/golang/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockService) Create(arg0 context.Context, arg1 *block.Block) (*block.Block, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(*block.Block)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockServiceMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockService)(nil).Create), arg0, arg1)
}

// GetBlockByName mocks base method.
func (m *MockService) GetBlockByName(arg0 context.Context, arg1 string) ([]*block.Block, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlockByName", arg0, arg1)
	ret0, _ := ret[0].([]*block.Block)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlockByName indicates an expected call of GetBlockByName.
func (mr *MockServiceMockRecorder) GetBlockByName(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlockByName", reflect.TypeOf((*MockService)(nil).GetBlockByName), arg0, arg1)
}

// GetBlockByNameAndVersion mocks base method.
func (m *MockService) GetBlockByNameAndVersion(arg0 context.Context, arg1, arg2 string) (*block.Block, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlockByNameAndVersion", arg0, arg1, arg2)
	ret0, _ := ret[0].(*block.Block)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlockByNameAndVersion indicates an expected call of GetBlockByNameAndVersion.
func (mr *MockServiceMockRecorder) GetBlockByNameAndVersion(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlockByNameAndVersion", reflect.TypeOf((*MockService)(nil).GetBlockByNameAndVersion), arg0, arg1, arg2)
}

// GetBlocksWithLatestVersion mocks base method.
func (m *MockService) GetBlocksWithLatestVersion(arg0 context.Context) ([]*block.Block, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlocksWithLatestVersion", arg0)
	ret0, _ := ret[0].([]*block.Block)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlocksWithLatestVersion indicates an expected call of GetBlocksWithLatestVersion.
func (mr *MockServiceMockRecorder) GetBlocksWithLatestVersion(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlocksWithLatestVersion", reflect.TypeOf((*MockService)(nil).GetBlocksWithLatestVersion), arg0)
}
