// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/example/clay/registry/pkg/block (interfaces: Service)
//
// Generated by this command:
//
//	mockgen --build_flags=--mod=mod -package mock_block -destination pkg/block/mock/block.go github.com/example/clay/registry/pkg/block Service
//

// Package mock_block is a generated GoMock package.
package mock_block

import (
	context "context"
	reflect "reflect"

	block "github.com/example/clay/registry/pkg/block"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockService) Create(ctx context.Context, arg1 *block.Block) (*block.Block, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, arg1)
	ret0, _ := ret[0].(*block.Block)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockServiceMockRecorder) Create(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockService)(nil).Create), ctx, arg1)
}

// GetBlockByName mocks base method.
func (m *MockService) GetBlockByName(ctx context.Context, name string) ([]*block.Block, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlockByName", ctx, name)
	ret0, _ := ret[0].([]*block.Block)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlockByName indicates an expected call of GetBlockByName.
func (mr *MockServiceMockRecorder) GetBlockByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlockByName", reflect.TypeOf((*MockService)(nil).GetBlockByName), ctx, name)
}

// GetBlockByNameAndVersion mocks base method.
func (m *MockService) GetBlockByNameAndVersion(ctx context.Context, name, version string) (*block.Block, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlockByNameAndVersion", ctx, name, version)
	ret0, _ := ret[0].(*block.Block)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlockByNameAndVersion indicates an expected call of GetBlockByNameAndVersion.
func (mr *MockServiceMockRecorder) GetBlockByNameAndVersion(ctx, name, version any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlockByNameAndVersion", reflect.TypeOf((*MockService)(nil).GetBlockByNameAndVersion), ctx, name, version)
}

// GetBlocksWithLatestVersion mocks base method.
func (m *MockService) GetBlocksWithLatestVersion(ctx context.Context) ([]*block.Block, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlocksWithLatestVersion", ctx)
	ret0, _ := ret[0].([]*block.Block)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlocksWithLatestVersion indicates an expected call of GetBlocksWithLatestVersion.
func (mr *MockServiceMockRecorder) GetBlocksWithLatestVersion(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlocksWithLatestVersion", reflect.TypeOf((*MockService)(nil).GetBlocksWithLatestVersion), ctx)
}
