name: "Build latest documentation for Ramen"

on:
  push:
    branches: ["main"]

jobs:
  build-mkdocs:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.8.1"]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          pip install -r python/requirements/requirements-dev.txt
          pip install --index-url ${{ secrets.MATTER_INDEX_URL }} matter
          pip install coverage mypy==0.971 flake8 isort pre-commit
      - name: Build docs
        run: |
          make build-docs
          cp .gitignore ./python/mkdocs/site/
          cp ./python/mkdocs/Dockerfile ./python/mkdocs/site
      - name: push documentation to latest-docs
        uses: casperdcl/push-dir@v1
        with:
          message: latest-ify ramen documentation (${{ github.sha }})
          branch: latest-docs
          dir: ./python/mkdocs/site

  build-push-container:
    needs: build-mkdocs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: "latest-docs"

      - name: Vault Secrets
        uses: hashicorp/vault-action@v2.4.0
        id: secrets
        with:
          url: http://vault.example.com:8200
          method: token
          tlsSkipVerify: true
          token: ${{ secrets.VAULT_TOKEN }}
          secrets: |
            kv/data/orbit acr_password | ACR_PASSWORD;
            kv/data/orbit acr_registry | ACR_REGISTRY;
            kv/data/orbit acr_username | ACR_USERNAME
      - name: "Build and push image"
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.ACR_REGISTRY }}
          username: ${{ env.ACR_USERNAME }}
          password: ${{ env.ACR_PASSWORD }}
      - run: |
          docker build . -t ${{ env.ACR_REGISTRY }}/ramen-documentation:latest -f Dockerfile
          docker push ${{ env.ACR_REGISTRY }}/ramen-documentation:latest

  apply-k8s-script:
    needs: build-push-container
    runs-on: ubuntu-20.04
    container:
      image: alpine/helm
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        id: install
      - name: "Deploy ramen docs"
        run: |
          echo "--This is running in alpine/helm Docker image--"
          apk update
          apk add bash py-pip curl
          apk add --virtual=build gcc libffi-dev musl-dev openssl-dev python3-dev make
          pip --no-cache-dir install -U pip
          pip --no-cache-dir install azure-cli
          apk del --purge build
          az login --service-principal --username ${{ secrets.SP_APP_ID }} --tenant ${{ secrets.SP_TENANT_ID }} --password ${{ secrets.SP_PASSWORD }}
          az aks get-credentials -n aks-k2-test -g rg-platform-test
          cd ./scripts
          kubectl apply -f host-docs.yaml
          kubectl rollout restart deployment "ramen-docs" -n "mlops"

      - id: get_ip
        run: |
          ramen_ip=$(kubectl get services -n mlops ramen-docs --output jsonpath='{.status.loadBalancer.ingress[0].ip}')
          echo "ramen_ip=$ramen_ip" >> $GITHUB_OUTPUT
          echo "ramen_ip=$ramen_ip"

      # - name: "Update on Github issues"
      #   uses: peter-evans/create-or-update-comment@v2
      #   with:
      #     edit-mode: replace
      #     comment-id: 1406538941
      #     body: |
      #       Latest IP for **ramen**'s documentation: `${{ steps.get_ip.outputs.ramen_ip }}`
