name: "Run tests and lint check"

on:
  pull_request:
    branches: ["main"]

jobs:
  ci-all-tests:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8.1"]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          pip install -r python/requirements/requirements-dev.txt
          pip install --index-url https://${{ secrets.GITLAB_TOKEN_NAME }}:${{ secrets.GITLAB_TOKEN_PASS }}@gitlab.com/api/v4/projects/38508365/packages/pypi/simple matter
          pip install coverage pre-commit
      - name: Run Pytest
        working-directory: ./python
        run: |
          coverage run -m pytest -v --durations=50 --junitxml=results-${{ runner.os }}-py${{ matrix.python-version }}.xml
      - name: Upload Pytest Results
        if: ${{ !failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: pytest-results-${{ runner.os }}-py${{ matrix.python-version }}
          path: python/results-${{ runner.os }}-py${{ matrix.python-version }}.xml
      - name: Coverage
        working-directory: ./python
        if: ${{ !failure() }}
        run: |
          coverage report
          coverage xml
      - name: Ruff Check
        uses: chartboost/ruff-action@v1
        with:
          src: "./python"

      - name: Lint with Pyright
        uses: jakebailey/pyright-action@v1
        with:
          version: 1.1.343

      - name: Docs Build Test
        run: |
          make build-docs
