
name: Release clay CLI

on:
    push:
      tags:
        - '**'

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4


      - name: Configure private token url
        env:
          GO_RELEASE_TOKEN: ${{ secrets.GO_RELEASE }}
        run: |
          git config --global url."https://${GO_RELEASE_TOKEN}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GO_RELEASE }}
