theme:
  name: material
  icon:
    admonition:
      note: fontawesome/solid/note-sticky
    pymdownx.details:
      tip: fontawesome/solid/bullhorn
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  # logo: img/favicon.png
site_name: Clay Documentation
repo_name: Clay
repo_url: https://github.com/example/clay
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - attr_list
  - md_in_html
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - admonition
  - toc:
      permalink: "#"

extra:
  version:
    provider: mike
plugins:
  - search
  - autorefs
  - schema_reader:
      include:
        - ./docs/block-spec-schema.json
  - mkdocstrings:
      enable_inventory: true
      handlers:
        python:
          paths: ["../python"]
          options:
            docstring_style: google
            show_root_toc_entry: false
            heading_level: 4
            show_source: true
            show_bases: false
            show_object_full_path: true
          import:
            - url: https://docs.python-requests.org/en/master/objects.inv
            - url: https://docs.python.org/3.9/objects.inv
            - url: https://docs.pydantic.dev/latest/objects.inv
            - url: https://typing-extensions.readthedocs.io/en/latest/objects.inv
          domains: ["py", "std"]

nav:
  - Home: "index.md"
  - 10000 Feet View: "overview.md"
  - Five Minute Blitz: "blitz-concepts.md"
  - Getting Started: "getting-started.md"
  - Tutorial: "model-development.md"
  - Input/Output: "IO.md"
  - Block Specification: "spec.md"
  - Indicating Model Progress: "progress.md"
  - Checklist: "checklist.md"
  - Do's and don'ts: "dos-dont.md"
  - FAQs: "faq.md"
  - API Reference: "api-reference.md"
  - CLI Reference: "cli-reference.md"
  - Benchmarking Models: "benchmarking.md"
